-- =============================================
-- MIGRATION: Change IDs from UUID to BIGINT
-- =============================================

-- Disable RLS temporarily to allow dropping tables if needed (though DROP TABLE usually ignores RLS)
-- We will drop tables in reverse order of dependencies

DROP TABLE IF EXISTS public.payments CASCADE;
DROP TABLE IF EXISTS public.social_aid_applications CASCADE;
DROP TABLE IF EXISTS public.documents CASCADE;
DROP TABLE IF EXISTS public.kumbaras CASCADE;
DROP TABLE IF EXISTS public.donations CASCADE;
DROP TABLE IF EXISTS public.members CASCADE;
DROP TABLE IF EXISTS public.beneficiaries CASCADE;

-- Note: users and audit_logs are preserved (partially)
-- We need to modify audit_logs to handle BIGINT record_ids (by storing as TEXT)
ALTER TABLE public.audit_logs ALTER COLUMN record_id TYPE TEXT;

-- =============================================
-- MEMBERS TABLE (Üyeler) - BIGINT ID
-- =============================================
CREATE TABLE IF NOT EXISTS public.members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tc_kimlik_no TEXT NOT NULL UNIQUE,
  ad TEXT NOT NULL,
  soyad TEXT NOT NULL,
  email TEXT,
  telefon TEXT NOT NULL,
  cinsiyet TEXT NOT NULL CHECK (cinsiyet IN ('erkek', 'kadin')),
  dogum_tarihi DATE,
  adres TEXT,
  uye_turu TEXT NOT NULL DEFAULT 'standart' CHECK (uye_turu IN ('standart', 'onursal', 'fahri')),
  kayit_tarihi DATE NOT NULL DEFAULT CURRENT_DATE,
  aidat_durumu TEXT NOT NULL DEFAULT 'beklemede' CHECK (aidat_durumu IN ('odendi', 'beklemede', 'gecikti')),
  notlar TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- DONATIONS TABLE (Bağışlar) - BIGINT ID
-- =============================================
CREATE TABLE IF NOT EXISTS public.donations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bagisci_adi TEXT NOT NULL,
  tutar DECIMAL(12, 2) NOT NULL,
  currency TEXT NOT NULL DEFAULT 'TRY' CHECK (currency IN ('TRY', 'EUR', 'USD')),
  amac TEXT NOT NULL,
  odeme_yontemi TEXT NOT NULL CHECK (odeme_yontemi IN ('nakit', 'havale', 'kredi_karti', 'kumbara')),
  makbuz_no TEXT,
  tarih DATE NOT NULL DEFAULT CURRENT_DATE,
  aciklama TEXT,
  member_id BIGINT REFERENCES public.members(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- BENEFICIARIES TABLE (İhtiyaç Sahipleri) - BIGINT ID
-- =============================================
CREATE TABLE IF NOT EXISTS public.beneficiaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tc_kimlik_no TEXT NOT NULL UNIQUE,
  ad TEXT NOT NULL,
  soyad TEXT NOT NULL,
  telefon TEXT NOT NULL,
  email TEXT,
  adres TEXT,
  il TEXT,
  ilce TEXT,
  cinsiyet TEXT NOT NULL CHECK (cinsiyet IN ('erkek', 'kadin')),
  dogum_tarihi DATE,
  medeni_hal TEXT,
  egitim_durumu TEXT,
  meslek TEXT,
  aylik_gelir DECIMAL(12, 2),
  hane_buyuklugu INTEGER,
  durum TEXT NOT NULL DEFAULT 'aktif' CHECK (durum IN ('aktif', 'pasif', 'beklemede')),
  ihtiyac_durumu TEXT NOT NULL DEFAULT 'orta' CHECK (ihtiyac_durumu IN ('acil', 'yuksek', 'orta', 'dusuk')),
  kategori TEXT,
  parent_id BIGINT REFERENCES public.beneficiaries(id) ON DELETE SET NULL,
  relationship_type TEXT CHECK (relationship_type IN ('İhtiyaç Sahibi Kişi', 'Bakmakla Yükümlü Olunan Kişi')),
  notlar TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- KUMBARAS TABLE (Kumbaralar) - BIGINT ID
-- =============================================
CREATE TABLE IF NOT EXISTS public.kumbaras (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kod TEXT NOT NULL UNIQUE,
  konum TEXT NOT NULL,
  durum TEXT NOT NULL DEFAULT 'aktif' CHECK (durum IN ('aktif', 'pasif', 'toplandi', 'kayip')),
  sorumlu_id BIGINT REFERENCES public.members(id) ON DELETE SET NULL,
  son_toplama_tarihi TIMESTAMPTZ,
  toplam_toplanan DECIMAL(12, 2) NOT NULL DEFAULT 0,
  notlar TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- SOCIAL AID APPLICATIONS TABLE - BIGINT ID
-- =============================================
CREATE TABLE IF NOT EXISTS public.social_aid_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  basvuran_id BIGINT NOT NULL REFERENCES public.beneficiaries(id) ON DELETE CASCADE,
  yardim_turu TEXT NOT NULL,
  talep_edilen_tutar DECIMAL(12, 2),
  onaylanan_tutar DECIMAL(12, 2),
  durum TEXT NOT NULL DEFAULT 'beklemede' CHECK (durum IN ('beklemede', 'inceleniyor', 'onaylandi', 'reddedildi')),
  basvuru_tarihi DATE NOT NULL DEFAULT CURRENT_DATE,
  degerlendirme_tarihi DATE,
  gerekce TEXT,
  notlar TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- PAYMENTS TABLE - BIGINT ID
-- =============================================
CREATE TABLE IF NOT EXISTS public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id BIGINT NOT NULL REFERENCES public.social_aid_applications(id) ON DELETE CASCADE,
  beneficiary_id BIGINT NOT NULL REFERENCES public.beneficiaries(id) ON DELETE CASCADE,
  tutar DECIMAL(12, 2) NOT NULL,
  odeme_tarihi DATE NOT NULL DEFAULT CURRENT_DATE,
  odeme_yontemi TEXT NOT NULL CHECK (odeme_yontemi IN ('nakit', 'havale', 'elden')),
  durum TEXT NOT NULL DEFAULT 'beklemede' CHECK (durum IN ('beklemede', 'odendi', 'iptal')),
  notlar TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- DOCUMENTS TABLE - BIGINT ID
-- =============================================
CREATE TABLE IF NOT EXISTS public.documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  beneficiary_id BIGINT NOT NULL REFERENCES public.beneficiaries(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  file_path TEXT NOT NULL,
  file_type TEXT NOT NULL,
  file_size INTEGER NOT NULL,
  document_type TEXT NOT NULL CHECK (document_type IN ('kimlik', 'ikamet', 'saglik', 'gelir', 'diger')),
  uploaded_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- RE-APPLY INDEXES
-- =============================================
CREATE INDEX IF NOT EXISTS idx_members_tc_kimlik ON public.members(tc_kimlik_no);
CREATE INDEX IF NOT EXISTS idx_members_ad_soyad ON public.members(ad, soyad);
CREATE INDEX IF NOT EXISTS idx_donations_tarih ON public.donations(tarih DESC);
CREATE INDEX IF NOT EXISTS idx_donations_amac ON public.donations(amac);
CREATE INDEX IF NOT EXISTS idx_beneficiaries_tc_kimlik ON public.beneficiaries(tc_kimlik_no);
CREATE INDEX IF NOT EXISTS idx_beneficiaries_durum ON public.beneficiaries(durum);
CREATE INDEX IF NOT EXISTS idx_beneficiaries_ihtiyac ON public.beneficiaries(ihtiyac_durumu);
CREATE INDEX IF NOT EXISTS idx_beneficiaries_parent_id ON public.beneficiaries(parent_id);
CREATE INDEX IF NOT EXISTS idx_beneficiaries_relationship_type ON public.beneficiaries(relationship_type);
CREATE INDEX IF NOT EXISTS idx_kumbaras_kod ON public.kumbaras(kod);
CREATE INDEX IF NOT EXISTS idx_kumbaras_durum ON public.kumbaras(durum);
CREATE INDEX IF NOT EXISTS idx_applications_durum ON public.social_aid_applications(durum);
CREATE INDEX IF NOT EXISTS idx_applications_basvuran ON public.social_aid_applications(basvuran_id);
CREATE INDEX IF NOT EXISTS idx_payments_beneficiary ON public.payments(beneficiary_id);
CREATE INDEX IF NOT EXISTS idx_documents_beneficiary ON public.documents(beneficiary_id);
CREATE INDEX IF NOT EXISTS idx_documents_type ON public.documents(document_type);

-- =============================================
-- RE-ENABLE RLS
-- =============================================
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.beneficiaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kumbaras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_aid_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

-- =============================================
-- RE-APPLY POLICIES
-- =============================================

-- Members
CREATE POLICY "Authenticated users can view members" ON public.members
  FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can manage members" ON public.members
  FOR ALL USING (auth.role() = 'authenticated');

-- Donations
CREATE POLICY "Authenticated users can manage donations" ON public.donations
  FOR ALL USING (auth.role() = 'authenticated');

-- Beneficiaries
CREATE POLICY "Authenticated users can manage beneficiaries" ON public.beneficiaries
  FOR ALL USING (auth.role() = 'authenticated');

-- Kumbaras
CREATE POLICY "Authenticated users can manage kumbaras" ON public.kumbaras
  FOR ALL USING (auth.role() = 'authenticated');

-- Applications
CREATE POLICY "Authenticated users can manage applications" ON public.social_aid_applications
  FOR ALL USING (auth.role() = 'authenticated');

-- Payments
CREATE POLICY "Authenticated users can manage payments" ON public.payments
  FOR ALL USING (auth.role() = 'authenticated');

-- Documents
CREATE POLICY "Authenticated users can manage documents" ON public.documents
  FOR ALL USING (auth.role() = 'authenticated');

-- =============================================
-- RE-APPLY TRIGGERS
-- =============================================
CREATE TRIGGER update_members_updated_at BEFORE UPDATE ON public.members FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_beneficiaries_updated_at BEFORE UPDATE ON public.beneficiaries FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_kumbaras_updated_at BEFORE UPDATE ON public.kumbaras FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_applications_updated_at BEFORE UPDATE ON public.social_aid_applications FOR EACH ROW EXECUTE FUNCTION update_updated_at();
